"""Add stress testing tables for comprehensive stress tests

Revision ID: b5cd2cea0507
Revises: 5c561b79e1f3
Create Date: 2025-08-04 16:10:21.393757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cd2cea0507'
down_revision: Union[str, Sequence[str], None] = '5c561b79e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
