"""Add Agent tables (conversations, messages, preferences)

Revision ID: 129ae82e72ca
Revises: 99219061f7b0
Create Date: 2025-08-28 08:23:41.636516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '129ae82e72ca'
down_revision: Union[str, Sequence[str], None] = '99219061f7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('provider_run_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_conversations'))
    )
    op.create_index('idx_agent_conversations_created_at', 'agent_conversations', ['created_at'], unique=False)
    op.create_index('idx_agent_conversations_provider_thread_id', 'agent_conversations', ['provider_thread_id'], unique=False)
    op.create_index('idx_agent_conversations_user_id', 'agent_conversations', ['user_id'], unique=False)
    op.create_table('agent_user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_mode', sa.String(length=50), nullable=False),
    sa.Column('preferred_model', sa.String(length=100), nullable=True),
    sa.Column('code_interpreter_enabled', sa.Boolean(), nullable=False),
    sa.Column('tool_calls_enabled', sa.Boolean(), nullable=False),
    sa.Column('streaming_enabled', sa.Boolean(), nullable=False),
    sa.Column('user_context', sa.String(length=2000), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_agent_user_preferences_user_id'))
    )
    op.create_index('idx_agent_user_preferences_user_id', 'agent_user_preferences', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_token_ms', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], name=op.f('fk_agent_messages_conversation_id_agent_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index('idx_agent_messages_conversation_id', 'agent_messages', ['conversation_id'], unique=False)
    op.create_index('idx_agent_messages_created_at', 'agent_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_messages_created_at', table_name='agent_messages')
    op.drop_index('idx_agent_messages_conversation_id', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('idx_agent_user_preferences_user_id', table_name='agent_user_preferences')
    op.drop_table('agent_user_preferences')
    op.drop_index('idx_agent_conversations_user_id', table_name='agent_conversations')
    op.drop_index('idx_agent_conversations_provider_thread_id', table_name='agent_conversations')
    op.drop_index('idx_agent_conversations_created_at', table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###
