"""Add etf_proxy and display_order to factor_definitions

Revision ID: 5874f3dd4e4d
Revises: 81d5d976093e
Create Date: 2025-07-15 18:59:30.304898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5874f3dd4e4d'
down_revision: Union[str, Sequence[str], None] = '81d5d976093e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factor_definitions', sa.Column('etf_proxy', sa.String(length=10), nullable=True))
    op.add_column('factor_definitions', sa.Column('display_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factor_definitions', 'display_order')
    op.drop_column('factor_definitions', 'etf_proxy')
    # ### end Alembic commands ###
