"""add_alerts_tables_properly

Revision ID: 5ad41758f3a9
Revises: f9ca4c5d886b
Create Date: 2025-08-26 17:27:44.030961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad41758f3a9'
down_revision: Union[str, Sequence[str], None] = 'f9ca4c5d886b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('EXPIRATION_RISK', 'CONCENTRATION', 'RISK_LIMIT', 'POSITION_CHANGE', 'MARKET_MOVE', 'CORRELATION', name='alerttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_alert_rules_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alert_rules_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('EXPIRATION_RISK', 'CONCENTRATION', 'RISK_LIMIT', 'POSITION_CHANGE', 'MARKET_MOVE', 'CORRELATION', name='alerttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISMISSED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('positions_affected', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_alerts_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
